language: ruby
rvm:
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 2.0
  - 1.9
  - jruby
  - rubinius
  - rubinius-2
  - rubinius-3
  - ruby-head
  - jruby
matrix:
  allow_failures:
    - rvm: rubinius
    - rvm: rubinius-2
    - rvm: rubinius-3
